---
# tasks file for /etc/ansible/roles/nginx

- name: installing a list of packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

- name: installing pip
  yum:
    name: python-pip
    state: latest
    enablerepo: epel

- name: installing docker-py
  pip:
    name: docker-py

- name: adding Docker stable repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable

- name: changing SELinux mode to permissive, logging actions that would be blocked
  selinux:
    policy: targeted
    state: permissive

- name: installing Docker CE
  yum:
    name: docker-ce
    state: latest

- name: enabling Docker and ensuring it is running
  systemd:
    name: docker
    enabled: yes
    state: started

- name: adding the 'worker' user to the 'docker' group
  user:
    name: worker
    groups: docker
    append: yes

- name: copying the nginx config file to the Docker host
  copy:
    src: /etc/ansible/roles/nginx/templates/nginx.conf
    dest: /home/worker/nginx.conf

- name: ensuring nginx container is running
  docker_container:
    name: nginx
    state: started
    restart: yes
    image: nginx:latest
    pull: yes
    ports:
     - "80:80"
     - "5000:5000"
    networks:
     - name: nice_net
       ipv4_address: 172.30.1.13
    networks_cli_compatible: no
    volumes:
      - /home/worker/nginx.conf:/etc/nginx/nginx.conf
