---
# tasks file for /etc/ansible/roles/webapp
- include_vars: dh_password.yml

- name: installing a list of packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

- name: installing pip
  yum:
    name: python-pip
    state: latest
    enablerepo: epel

- name: installing docker-py
  pip:
    name: docker-py

- name: adding Docker stable repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable

- name: changing SELinux mode to permissive, logging actions that would be blocked
  selinux:
    policy: targeted
    state: permissive

- name: installing Docker CE
  yum:
    name: docker-ce
    state: latest

- name: enabling Docker and ensuring it is running
  systemd:
    name: docker
    enabled: yes
    state: started

- name: adding the 'jenkins' user to the 'docker' group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: logining into DockerHub...
  docker_login:
    username: kastilochagin
    email: castillo.chagin@gmail.com
    password: "{{dh_password}}"

- name: creating a Docker network
  docker_network:
    name: nice_net
    ipam_config:
      - subnet: 172.30.1.0/24
        gateway: 172.30.1.100

- name: ensuring the 1st web application container is running
  docker_container:
    name: app1
    hostname: app1
    state: started
    image: kastilochagin/priv:app
    pull: yes
    networks:
     - name: nice_net
       ipv4_address: 172.30.1.1
    networks_cli_compatible: no

- name: ensuring the 2nd web application container is running
  docker_container:
    name: app2
    hostname: app2
    state: started
    image: kastilochagin/priv:app
    pull: yes
    networks:
     - name: nice_net
       ipv4_address: 172.30.1.2
    networks_cli_compatible: no

- name: ensuring the 3rd web application container is running
  docker_container:
    name: app3
    hostname: app3
    state: started
    image: kastilochagin/priv:app
    pull: yes
    networks:
     - name: nice_net
       ipv4_address: 172.30.1.3
    networks_cli_compatible: no
